#!/usr/bin/env bash
set -o errexit   # exit on error
set -o pipefail  # exit on error in pipes
set -o nounset   # exit on unset variable
ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."
cd "$ROOT_DIR"


# commit new docs
scripts/docs/clean
scripts/docs/build
git checkout gh-pages
