#!/usr/bin/env bash
set -o errexit   # exit on error
set -o pipefail  # exit on error in pipes
set -o nounset   # exit on unset variable
ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."
cd "$ROOT_DIR"


# generate updated docs
scripts/docs/clean
scripts/docs/build


# checkout gh-pages, clean
git checkout gh-pages
rm -rf search *.html *.png *.svg *.css *.js


# install updated docs
cp -r docs/site/html/* .
git add --update
git add --force search *.html *.png *.svg *.css *.js


# commit and push
if git commit -m "📝 generated updated docs" ; then
  git push
  git checkout main
  exit 0
else
  echo "no changes to commit"
  git checkout main
  exit 1
fi
