#!/usr/bin/env bash
set -o errexit   # exit on error
set -o pipefail  # exit on error in pipes
set -o nounset   # exit on unset variable
ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."
cd "$ROOT_DIR"


# generate updated docs
scripts/docs/clean
scripts/docs/build


# checkout, clean gh-pages
git checkout gh-pages
rm -rf search *.html *.png *.svg *.css *.js

# commit updated docs
cp -r docs/site/html/* .
git add --update
git add --force search *.html *.png *.svg *.css *.js
git commit -m "📝 generated updated docs"
git push


# clean up
rm -rf docs
git checkout main
