#!/usr/bin/env bash
set -o errexit   # exit on error
set -o pipefail  # exit on error in pipes
set -o nounset   # exit on unset variable
ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."
cd "$ROOT_DIR"


# constants
SITE_DIR="docs/site/html"


# check for site directory
if [ ! -d "$SITE_DIR" ]; then
  echo "documentation not found; did you build it?"
  exit 1
fi


cd "$SITE_DIR"


# call python's http.server, with args;
# background the server
set -o monitor
python -m http.server "$@" &


# open site in browser
sleep 1
open "http://localhost:8000"


# foreground the server;
# then user can ^C to stop it
fg
