name: Build


# execute unless tagged as release
on:
  push:
    branches: [ '**' ]


jobs:


  Build:
    runs-on: ubuntu-latest
    steps:

        # install latest python 3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # check out source code
      - uses: actions/checkout@v4

      # install conan
      - name: install conan
        run:  pip install --requirement requirements.txt

      # create default conan profile
      - name: create default conan profile
        run:  conan profile detect

      # install conan packages
      - name: install conan packages
        run:  scripts/install

      # build
      - name: build
        run:  scripts/create
