name: Build Shared Debug Package
on: push
jobs:
  BuildSharedDebugPackge:
    runs-on: ubuntu-latest
    steps:
      - name: install build tools
        run:  |
          sudo apt-get update
          sudo apt-get install build-essential
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: actions/checkout@v4
      - name: install conan
        run:  pip install --requirement requirements.txt
      - name: create default conan profile
        run:  conan profile detect
      - name: build static release
        run:  |
          scripts/install --options */*:shared=False --settings build_type=Release
          scripts/create  --options */*:shared=False --settings build_type=Release
      - name: build static debug
        run:  |
          scripts/install --options */*:shared=False --settings build_type=Debug
          scripts/create  --options */*:shared=False --settings build_type=Debug
      - name: build shared release
        run:  |
          scripts/install --options */*:shared=True --settings build_type=Release
          scripts/create  --options */*:shared=True --settings build_type=Release
      - name: build shared debug
        run:  |
          scripts/install --options */*:shared=True --settings build_type=Debug
          scripts/create  --options */*:shared=True --settings build_type=Debug
