name: Build All


# execute unless tagged as release
on:
  push:
    tags:
      - 'releases/**'


jobs:

  BuildAll:

    # build configurations
    strategy:
      matrix:

        # build ubuntu, windows, macos
        os:
         - ubuntu-latest
         - windows-latest
         - macos-latest

        # build shared, static
        shared:
          - False
          - True

        # build release, debug
        build_type:
          - Release
          - Debug


    # operating system
    runs-on: ${{ matrix.os }}


    steps:

      # use latest python 3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # checkout source code
      - uses: actions/checkout@v4

      # install python packages (conan)
      - name: install conan
        run:  pip install --requirement requirements.txt

      # create conan profile
      - name: create default conan profile
        run:  conan profile detect

      # install conan packages
      - name: install conan packages
        run:  scripts/install --options */*:shared=${{ matrix.shared }} --settings build_type=${{ matrix.build_type }}

      # build
      - name: build
        run:  scripts/create --options */*:shared=${{ matrix.shared }} --settings build_type=${{ matrix.build_type }}
