name: Build Static Debug Package
on: push
jobs:
  BuildStaticDebugPackge:
    runs-on: ubuntu-latest
    steps:
      - name: install build tools
        run:  |
          sudo apt-get update
          sudo apt-get install build-essential
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: actions/checkout@v4
      - name: install conan
        run:  pip install --requirement requirements.txt
      - name: create default conan profile
        run:  conan profile detect
      - name: install requirements
        run:  scripts/install --options */*:Static=False --settings build_type=Debug
      - name: create and test package
        run:  scripts/create  --options */*:Static=False --settings build_type=Debug
