name: Publish Docs


# execute on build all
on:
  workflow_run:
    workflows:
      - Build All
    branches:
      - main
    types:
      - completed


jobs:

  PublishDocs:

    # linux host
    runs-on: ubuntu-latest

    # need write permissions to push to gh-pages
    permissions:
      contents: write


    steps:

      # check out source
      - uses: actions/checkout@v4

      # install doxygen
      - name: install doxygen
        run:  |
          sudo apt-add-repository universe
          sudo apt-get update
          sudo apt-get install doxygen

      # run doxygen
      - name: build docs
        run:  scripts/docs/build

      # push to gh-pages to push
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site/html
