name: Release Source


# execute on release build
on:
  workflow_run:
    workflows: [ "Build All"   ]
    tags:      [ "releases/**" ]
    types:     [ completed     ]


jobs:


  ReleaseSource:
    runs-on: ubuntu-latest
    steps:

      # check out source code
      - uses: actions/checkout@v4

      # git archive to zip
      - name: archive
        run:  scripts/archive

      # release
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/rohdeschwarz-src-*.zip"
